version: '3.8'

services:
    products:
        build: ./products
        restart: always
        hostname: products
        networks:
            - backend
        depends_on:
            - db
        ports:
            - 3000:3000
    transactions:
        build: ./transactions
        restart: always
        hostname: transactions
        networks:
            - backend
        depends_on:
            - db
        ports:
            - 3001:9229
    db:
        image : mongo:latest
        container_name: mongodb
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        networks:
            - backend
        restart: always

networks:
    backend:
        driver: bridge