version: '3.8'

services:
    products:
        build: ./products
        hostname: products
        networks:
            - backend
        links:
            - db
        ports:
            - 3000:3000
    transactions:
        build: ./transactions
        hostname: transactions
        networks:
            - backend
        links:
            - db
        ports:
            - 3001:9229
    db:
        image: 'mongo:latest'
        restart: always
        hostname: db
        environment:
            MONGO_INITDB_DATABASE: testafg
        volumes:
            - "./db/init/:/docker-entrypoint-initdb.d/"
        networks:
            - backend
        ports:
            - 27017:27017

networks:
    backend:
        driver: bridge